### ISSUE TITLE
Crossline binary sensors falsely trigger on every 60s poll cycle when Baichuan TCP push subscription drops

### ISSUE THREAD

**Issue by andrewchaffe** [starkillerOG/reolink_aio#198]
# Reolink crossline binary sensors falsely report "detected" on every 60 second poll

---

## The problem

On an Elite Floodlight WiFi (directly connected, TCP push), the `crossline` binary sensors repeatedly report `on` when nothing is present. The Reolink app shows no detections, and the camera's own AI sensors (`binary_sensor.*_person`, `binary_sensor.*_motion`) correctly stay clear throughout.

Three observations point to the 60 second redundancy poll misreading the crossline state rather than to a genuine detection or a misconfigured line:

**1. Every activation lands on the exact same second-offset within the minute**

All 18 `off` to `on` transitions over a four hour window occurred at `:22.5` seconds past the minute:

```
17:34:22.516  17:46:22.539  17:52:22.569  17:58:22.648
18:13:22.542  18:16:22.528  18:17:22.514  18:20:22.543
19:25:22.522  19:28:22.520  19:29:22.567  19:48:22.564
19:53:22.586  19:59:22.605  20:00:22.542  20:06:22.535
20:20:22.585  20:25:22.530
```

This matches the documented 60 second polling interval for directly connected cameras exactly. Real line crossings do not occur on a fixed cadence.

**2. Two independent crossline rules fire within 3 milliseconds of each other**

Two separate lines are configured in the Reolink app ("Porch Line" and "Garage Line") covering physically different areas. They activate simultaneously, every time:

| Porch Line person | Garage Line person | Delta |
|---|---|---|
| 17:34:22.516552 | 17:34:22.518929 | 2.4 ms |
| 17:46:22.539899 | 17:46:22.542458 | 2.6 ms |
| 17:52:22.569852 | 17:52:22.572474 | 2.6 ms |
| 17:58:22.648456 | 17:58:22.651296 | 2.8 ms |
| 18:13:22.542596 | 18:13:22.544943 | 2.3 ms |

A person cannot cross two separate lines simultaneously. Both sensors are being set by the same code path, not by distinct detections.

**3. Genuine push events CLEAR the crossline sensors**

The `off` transitions coincide, to the millisecond, with `binary_sensor.driveway_motion` turning `on`:

| `driveway_motion` → on | crossline → off | Delta |
|---|---|---|
| 17:45:26.668642 | 17:45:26.669577 | 0.9 ms |
| 17:57:52.294719 | 17:57:52.295767 | 1.0 ms |
| 18:12:33.533154 | 18:12:33.534094 | 0.9 ms |
| 19:24:38.138915 | 19:24:38.139864 | 0.9 ms |
| 19:59:20.101701 | 19:59:20.102662 | 1.0 ms |

So the behaviour is inverted relative to expectation: the poll path **sets** the sensor, and the push path **clears** it.

## Suspected cause

Per the integration documentation, crossline/intrusion/linger/item sensors are marked `+` (push updates plus the 60 second redundancy poll), whereas motion and AI person/vehicle/animal sensors are marked `++` (TCP push, ONVIF push, ONVIF long polling, or 5 second fast polling, plus the 60 second poll).

Crossline sensors therefore have no fallback event delivery chain. This system logs frequent Baichuan subscription drops:

```
ERROR reolink_aio.baichuan.baichuan
Baichuan host 192.168.x.x: lost event subscription after 3.15 s and failed to reestablished connection
Baichuan host 192.168.x.x: lost event subscription after 57.84 s, last reestablish 58.58 s ago
Baichuan host 192.168.x.x: lost event subscription after 11.39 s and failed to reestablished connection
```

When the TCP push subscription is down, the `++` sensors degrade gracefully via their fallback chain and continue to report correctly. The `+` crossline sensors fall back solely to the 60 second poll, which appears to parse the crossline state incorrectly and default it to "detected".

## What was ruled out

- **Corrupted or stale rule configuration.** Both crossline rules were deleted in the Reolink app and recreated from scratch. Both new rules exhibit identical behaviour immediately.
- **Weak Wi-Fi signal.** `sensor.*_wi_fi_signal` sat between -55 and -58 dBm throughout the affected window, with no correlation between signal dips and false triggers.
- **Sensitivity setting.** Crossline sensitivity is 43, below the camera's own AI person sensitivity of 40 to 47 range. Sensitivity does not explain a fixed 60 second cadence.
- **Genuine detections.** `binary_sensor.driveway_person` remained `off` for the entire four hour window, and the Reolink app logged no events.

## What version of Home Assistant Core has the issue?

2026.8.1

## What type of installation are you running?

Home Assistant OS (Supervisor 2026.07.5, HAOS 18.2, aarch64)

## Integration causing the issue

Reolink

## Link to integration documentation

https://www.home-assistant.io/integrations/reolink/

## Diagnostics information

```
model:               Elite Floodlight WiFi
hardware version:    IPC_NT18NA68MPW

firmware version:    v3.2.0.6530_2606232191
reolink-aio:         0.21.8
event connection:    TCP push
Baichuan port:       9000
Baichuan connection: tcp
Baichuan only:       false
Baichuan fallbacks:  []
Broken cmds:         []
HTTPS:               true
HTTP(S) port:        443
ONVIF enabled:       true
RTSP enabled:        true
stream protocol:     rtsp
WiFi connection:     true
WiFi signal:         -58
is NVR:              false
is Hub:              false
is Battery:          false
supportCrossLineDetect: permit 6, ver 1
supportSmartAi:         permit 6, ver 7
smartAI (BC_abilities): 14
eventTypeVersion:       23
```

## Anything in the logs that might be useful?

```
Logger: reolink_aio.baichuan.baichuan
Source: runner.py:290
Level: ERROR

Baichuan host 192.168.x.x: lost event subscription after 3.15 s and failed to reestablished connection
Baichuan host 192.168.x.x: lost event subscription after 57.84 s, last reestablish 58.58 s ago
Baichuan host 192.168.x.x: lost event subscription after 11.39 s and failed to reestablished connection

Logger: homeassistant.components.reolink.coordinator
Source: helpers/update_coordinator.py:506
Level: ERROR

Error fetching reolink.Driveway data: Host 192.168.x.x:443: connection error:
Cannot connect to host 192.168.x.x:443 ssl:default [Connect call failed ('192.168.x.x', 443)]

Logger: reolink_aio.api
Source: components/reolink/host.py:930
Level: WARNING

ONVIF event with unknown rule: 'Non_Motor_VehicleDetect'
```

## Additional information

The false triggers hold the sensor `on` for extended periods (30 to 40 minutes in some cases), because nothing clears it until either a genuine motion push event arrives or the next poll flips it. This makes the sensors unusable as automation triggers, since a `for:` duration filter cannot distinguish the fault from a real detection.

The `ONVIF event with unknown rule: 'Non_Motor_VehicleDetect'` warning may or may not be related, but is included in case it is relevant to smart-event parsing on this firmware.

**Comment by starkillerOG** [comment]
Could you enable debug logging for about 3 minutes when on the troublesome HomeAssistant version?
[home-assistant.io/docs/configuration/troubleshooting#enabling-debug-logging](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging)

Please provide the diagnostic info file as well as the debug log file

**Comment by andrewchaffe** [comment]
[reolink-debug-trimmed.log](https://github.com/user-attachments/files/31045665/reolink-debug-trimmed.log)
[reolink-diagnostics.json](https://github.com/user-attachments/files/31045787/reolink-diagnostics.json)


Trimmed debug log and diagnostics attached, captured 2026-08-14 06:40 to 07:08 local (Australia/Sydney, UTC+10) while the fault was actively occurring. Nobody was on the property for the entire window, and the Reolink app showed no events.

Analysing the captured `GetEvents` payloads turned up something more specific than what I originally reported, and it contradicts part of my original hypothesis. Correcting that below.

## The camera reports a latched `people_state`, and it is mapped to the wrong entity

Across 19 consecutive 60 second polls (06:49:58 through 07:08:03), the `GetEvents` response from the camera was byte-identical every time:

```json
{
   "cmd" : "GetEvents",
   "code" : 0,
   "value" : {
      "ai" : {
         "crossline" : [
            { "index" : 0, "enable" : 0, "people_state" : 0, "vehicle_state" : 0, "dogcat_state" : 0, "support" : 1 },
            { "index" : 1, "enable" : 1, "people_state" : 1, "vehicle_state" : 0, "dogcat_state" : 0, "support" : 1 },
            { "index" : 2, "enable" : 0, "people_state" : 0, "vehicle_state" : 0, "dogcat_state" : 0, "support" : 1 }
         ],
         ...
```

Two separate problems are visible here.

### 1. Index mapping mismatch

I have two crossline entities registered:

| Entity unique_id suffix | Friendly name | HA state during the whole window |
|---|---|---|
| `..._crossline_person_1` | Crossline Porch Line 2 person | **off** (unchanged since 02:01:41) |
| `..._crossline_person_2` | Crossline Garage Line person | **on** (since 06:33:43, ~35 min) |

But the payload has `people_state: 1` on the entry whose `"index"` is **1**, and `people_state: 0` on the entries with `"index"` **0** and **2**.

So the entity suffixed `_1` did not reflect the payload entry with `"index": 1`. The states are shifted by one.

The mapping that fits the observed behaviour is 1-based positional enumeration over the list, i.e. entity `_N` reads array position `N-1`:

- entity `_1` ← array position 0 (`"index": 0`, people_state 0) → off ✓ matches observed
- entity `_2` ← array position 1 (`"index": 1`, people_state 1) → on ✓ matches observed

That would mean the parser is enumerating positionally rather than keying on the `"index"` field in each entry. I can't confirm that from the log alone, it's an inference from the state mapping, but the one-position shift itself is directly observable in the data above.

This also explains a detail from my original report: two physically separate lines appearing to trigger within 2 to 3 milliseconds of each other. If entity `_N` is reading position `N-1`, adjacent entities surface adjacent array entries from the same single parse pass.

### 2. `people_state` appears to latch and never clear

Independent of the mapping issue, the camera returned `people_state: 1` on every one of the 19 polls, continuously, for over 18 minutes, with nobody present. During that same period on the same device:

- `binary_sensor.driveway_person` (AI person) — `off` since 06:22:40
- `binary_sensor.driveway_motion` — `off` since 06:23:22
- `binary_sensor.driveway_vehicle` — `off` since 06:23:21

So the camera's own AI sensors correctly read clear while the `crossline[].people_state` field stayed stuck at 1. This suggests `people_state` in `GetEvents` is not a reliable instantaneous state on this firmware, it behaves more like a latched or "has triggered" flag. Rebooting the camera clears it; reloading the integration does not.

## Correction to my original report

I originally suggested the poll path was misparsing the crossline state and defaulting it to "detected". That was wrong. The parse reads a genuine value from the camera. The two actual problems are the index mapping shift, and the fact that the underlying `people_state` field latches.

## Likely same root cause as #179058

https://github.com/home-assistant/core/issues/179058 reports the same behaviour on the **same camera model and identical firmware** (Elite Floodlight WiFi F751W, v3.2.0.6530_2606232191), and identifies it as a regression: working on Core 2026.7.4, broken on 2026.8.1. That xenjke notes the older library failed to parse this list entirely (`'list' object has no attribute 'get'`) and points at the Smart AI `GetEvents` list parsing added in #176726 / #177134.

That fits what I'm seeing. Before the list parsing existed, these sensors were never driven from the poll, so the latched `people_state` was never surfaced. Now that the list is parsed, the latched value reaches the entities, via a mapping that also appears to be off by one.

## Environment

- Home Assistant Core 2026.8.1, Home Assistant OS 18.2, Supervisor 2026.07.5, aarch64
- reolink-aio 0.21.8
- Reolink Elite Floodlight WiFi (IPC_NT18NA68MPW), firmware v3.2.0.6530_2606232191
- Directly connected (not via NVR/Hub), `event connection: TCP push`, Baichuan port 9000
- Two crossline rules configured in the Reolink app; `supportSmartAi` permit 6 ver 7

**Comment by Motore** [comment]
Can confirm the same bug on identical hardware/firmware (Elite Floodlight WiFi, v3.2.0.6530_2606232191, reolink-aio 0.21.8, TCP push).

Diagnostics:
model:               Elite Floodlight WiFi
hardware version:    IPC_NT18NA68MPW
firmware version:    v3.2.0.6530_2606232191
reolink-aio:         0.21.8
event connection:    TCP push
Baichuan port:       9000
Baichuan connection: tcp
Baichuan only:       false
Baichuan fallbacks:  []
Broken cmds:         []
HTTPS:               true
HTTP(S) port:        443
ONVIF enabled:       true
RTSP enabled:        true
stream protocol:     rtsp
WiFi connection:     true
WiFi signal:         -60
is NVR:              false
is Hub:              false
is Battery:          false
supportCrossLineDetect: permit 6, ver 1
supportSmartAi:         permit 6, ver 7
smartAI (BC_abilities): 14
eventTypeVersion:       23

In my case it's even more consistent: a short ~4 minute debug capture contains 5 consecutive 60s polls (GetEvents), and every single one reports crossline index 0 as `people_state: 1` while the other two (unused) crossline indices correctly report 0:

13:37:45.719  crossline[0].people_state = 1
13:38:45.646  crossline[0].people_state = 1
13:39:45.719  crossline[0].people_state = 1
13:40:45.719  crossline[0].people_state = 1
13:41:45.675  crossline[0].people_state = 1

During the same window, the only real TCP push events (cmd_id 33) received all carry `<AItype>none</AItype>` — none of them report an AI/crossline type. So on this firmware the crossline sensor appears to get zero real push events and falls back entirely to the poll, which misreports it as detected on every single cycle.

**Comment by starkillerOG** [comment]
This upstream library commit should fix the issue: https://github.com/starkillerOG/reolink_aio/commit/e1e1ee54ea9cacd883494fcbd648576e8288ecf2

However there is clearly a bug in the firmware causing the GetEvents smart AI to latch.
Could you also report this bug to reolink support?

Thank you for reporting the issue.

**Comment by xenjke** [comment]
Still reproducible on Home Assistant Core 2026.8.3 with `reolink-aio==0.21.9` (diagnostics attached).

After one actual `Crossline - person` event, every subsequent `Crossline - person` notification was a duplicate.

An 8-minute debug capture shows the target camera returning `crossline[0].people_state=1` in every 60-second HTTP `GetEvents` poll. During the same capture, no TCP `cmd_id 33` payload from this camera contained `AItype=crossline` or a Smart AI event; they contained only vehicle/motion/`none`.

The HA automation only triggers when the crossline entity transitions to `on`, so the repeated notifications I'm getting means that it is still being re-triggered.

[reolink-debug-redacted.log](https://github.com/user-attachments/files/31353413/reolink-debug-redacted.log)
[reolink-diagnostics.json](https://github.com/user-attachments/files/31353412/reolink-diagnostics.json)

**Comment by andrewchaffe** [comment]
**Update: still occurring on reolink-aio 0.21.14 (HA Core 2026.9.0), after the 0.21.10 GetEvents change.**

0.21.10 disabled Smart AI parsing in HTTP `GetEvents` and home-assistant/core#179851 was marked as closing this issue. I confirmed in the 0.21.14 source that the smart AI branch in `api.py` is now a hard `continue`, so `GetEvents` genuinely cannot set these sensors any more. The false detections still happen.

### Yesterday, 5 September, 17:45 to 18:01 local

Seven `off` to `on` transitions on `binary_sensor.driveway_crossline_porch_entry_person`, every one at the same fraction of a second past the minute:

```
17:46:05.391  17:47:05.403  17:48:05.373  17:50:05.414
17:55:05.379  17:57:05.370  18:00:05.363
```

Spread across the seven: 38 ms. Same fixed 60 s phase as the original report, just a different offset after restarts.

**Both crossline lines on the same camera still flip together:**

| Porch Line person | Garage Line person | Delta |
|---|---|---|
| 18:00:05.363270 | 18:00:05.363670 | 0.4 ms |
| 18:01:17.765354 (off) | 18:01:17.765953 (off) | 0.6 ms |

My second Elite Floodlight WiFi, a separate config entry, did the same on its own phase at `:08`.

**`binary_sensor.driveway_person` did not change state once** in that window. It was `off` continuously from before 17:30 to after 18:15.

**Push events still clear the sensor:**

| `driveway_motion` → on | crossline → off | Delta |
|---|---|---|
| 17:45:45.682095 | 17:45:45.683128 | 1.0 ms |
| 17:46:26.851525 | 17:46:26.852510 | 1.0 ms |
| 17:49:34.012160 | 17:49:34.013166 | 1.0 ms |
| 17:59:29.007207 | 17:59:29.008145 | 0.9 ms |

So the inverted behaviour is unchanged: pushes clear, something on a 60 s cadence sets.

### Two corrections to my original report

**1. The title is wrong, and I would like to retitle it.** I blamed Baichuan subscription drops. Through the whole 5 September event the subscription was healthy. The only drop in the log was at 02:00, during the nightly HA backup. Subscription loss is not the trigger, so anything aimed at that layer will miss.

**2. It is intermittent, not continuous.** The sensor sat clean from 4 September 00:00 through to 16:41 on 5 September, latched for the window above, then cleared at 18:01. Across all of today, 6 September, the crossline sensors have tracked real detections correctly: short 5 to 10 second pulses that line up with `driveway_person` and `driveway_left_person` going `on`. So the sensors do work most of the time, and then a state gets stuck and every subsequent cycle re-asserts it until something clears it.

### Question

With `GetEvents` smart AI parsing disabled, the only remaining setter I can find is the `cmd_id 33` handler in `baichuan.py`, which resets all smart AI to `False` and then sets whatever appears in `smartAiTypeList`. Is it plausible that this firmware sends a periodic `AlarmEvent` carrying a `smartAiTypeList` that still contains the latched crossline location, so the reset-then-set logic re-asserts it every cycle? That would explain both the fixed cadence and why a genuine motion push, which presumably arrives with no crossline entry, clears it.

Worth noting from my August capture: across 19 minutes the affected camera (`192.168.1.12`) sent **zero** `cmd_id 33` pushes. Every push in that log came from a different Reolink camera on the same network, and all five carrying an `<AItype>` reported `none`. I did not put that in the original report and it may be relevant.

Happy to capture a fresh `reolink_aio` debug log the next time it latches if that would help. It is intermittent, so I cannot force it on demand.

### Vendor side

Reolink ticket 1878738 is open with their senior support team, escalating to R&D. I have answered their questions about the `GetEvents` request and response, and passed on the finding that the fault persists after the HTTP path was disabled in software, which points at the push channel rather than the HTTP API alone.
